# Generated by Django 3.1.2 on 2020-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=80, verbose_name='Apellidos(s)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('direction', models.CharField(max_length=100, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Proveedores',
            },
        ),
    ]
